apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-postgres
  namespace: bondtradex

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-postgres

  template:

    metadata:
      labels:
        app: auth-postgres

    spec:

      containers:

        - name: auth-postgres

          image: postgres:17

          ports:
            - containerPort: 5432

          env:

            - name: POSTGRES_DB
              value: auth_db

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: DB_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: DB_PASSWORD

          volumeMounts:

            - mountPath: /var/lib/postgresql/data
              name: postgres-storage

      volumes:

        - name: postgres-storage

          persistentVolumeClaim:
            claimName: auth-postgres-pvc