############################################
# Server
############################################
server.port=8082

############################################
# Application
############################################
spring.application.name=ioi-service

############################################
# PostgreSQL
############################################
spring.datasource.url=jdbc:postgresql://localhost:5432/ioi_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

############################################
# JPA / Hibernate
############################################
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

############################################
# Flyway
############################################
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
############################################
# Redis
############################################
spring.data.redis.host=localhost
spring.data.redis.port=6379
############################################
# OAuth2 Resource Server
############################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8081

############################################
# Actuator
############################################
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always

############################################
# Micrometer
############################################
management.metrics.tags.application=ioi-service

############################################
# Logging
############################################
logging.level.org.springframework.security=INFO
logging.level.com.bondtradex.ioi=INFO