############################################
# Server
############################################
server.port=8082

############################################
# Application
############################################
spring.application.name=ioi-service

############################################
# OAuth2 Resource Server
############################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8081

############################################
# Actuator
############################################
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always

############################################
# Micrometer
############################################
management.metrics.tags.application=ioi-service

############################################
# Logging
############################################
logging.level.org.springframework.security=INFO